name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  publish_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: Running Prettier Code Formatter
      run: npm run format:check --if-present
    - name: publish
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        GITHUB_TOKEN: ${{ secrets.CLIENT_SECRET }}
      run: npm run publish

  publish_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: Running Prettier Code Formatter
      run: npm run format:check --if-present
    - name: publish
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        GITHUB_TOKEN: ${{ secrets.CLIENT_SECRET }}
      run: npm run publish

  publish_on_win:
    runs-on: windows-latest
    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: Running Prettier Code Formatter
      run: npm run format:check --if-present
    - name: publish
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        GITHUB_TOKEN: ${{ secrets.CLIENT_SECRET }}
      run: npm run publish
